[package]
name = "homie-device"
version = "0.5.0"
authors = ["Andrew Walbran <qwandor@google.com>", "David Laban <alsuren@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A library for creating devices implementing the Homie convention for MQTT."
repository = "https://github.com/alsuren/mijia-homie/"
keywords = ["homie", "mqtt"]
categories = ["network-programming"]

[dependencies]
async-channel = "1.6.1"
futures = "0.3.17"
local_ipaddress = "0.1.3"
log = "0.4.14"
mac_address = "1.1.2"
rumqttc = "0.8.0"
tokio = "1.12.0"
thiserror = "1.0.29"

[dev-dependencies]
pretty_env_logger = "0.4.0"
rand = "0.8.1"
# TODO: Remove "io-util" once a new version of rumqttc is released which fixes
# https://github.com/bytebeamio/rumqtt/issues/294.
tokio = { version = "1.12.0", features = ["io-util", "macros", "rt", "rt-multi-thread", "time"] }
