[package]
name = "homie-controller"
version = "0.3.0"
authors = ["Andrew Walbran <qwandor@google.com>", "David Laban <alsuren@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A library for creating controllers to talk to devices implementing the Homie convention for MQTT."
repository = "https://github.com/alsuren/mijia-homie/"
keywords = ["homie", "mqtt"]
categories = ["network-programming"]

[dependencies]
log = "0.4.11"
rumqttc = "0.8.0"
thiserror = "1.0.23"

[dev-dependencies]
async-channel = "1.5.1"
futures = "0.3.8"
homie-device = { version = "0.5.0", path = "../homie-device" }
pretty_env_logger = "0.4.0"
rumqttd = "0.7.0"
rumqttlog = "0.7.0"
tokio = { version = "1.0.1", features = ["macros", "rt", "rt-multi-thread", "time"] }
